  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: Uptime-Kuma
    hostname: uptime-kuma
    environment:
      - PUID=${PUID:?err}    # User ID
      - PGID=${PGID:?err}    # Group ID
      - TZ=${TZ:?err}        # TimeZone
      - UMASK=${UMASK:?err}  # File Umask
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    volumes:
      - ${DOCKERFOLDER:?err}/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # Optional: for monitoring Docker containers
    ports:
      - 3001:3001 # HostPort:ContainerPort
    restart: always