  watchtower:
    image: containrrr/watchtower:latest
    container_name: Watchtower
    environment:
      - PUID=${PUID:?err}    # User ID
      - PGID=${PGID:?err}    # Group ID
      - TZ=${TZ:?err}        # TimeZone
      - UMASK=${UMASK:?err}  # File Umask
      - WATCHTOWER_DISABLE_CONTAINERS=immich_postgres,immich_redis
      - WATCHTOWER_SCHEDULE=0 2 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@sflservicesllc.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=steve.ling@sflservicesllc.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=mail.onling.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=true
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=25
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=SFL-MEDIA-001
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_HTTP_API_TOKEN= # Add your Token
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
      - WATCHTOWER_TIMEOUT=30s
      - DOCKER_API_VERSION=1.44 # Add this for Docker Environment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8006:8080
    #command: --interval 86400 --debug list of containers to monitor
    restart: always